export const accountActions = {
  REGISTER_START: 'REGISTER_START',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAIL: 'REGISTER_FAIL',

  CONFIRM_EMAIL_START: 'CONFIRM_EMAIL_START',
  CONFIRM_EMAIL_SUCCESS: 'CONFIRM_EMAIL_SUCCESS',
  CONFIRM_EMAIL_FAIL: 'CONFIRM_EMAIL_FAIL',

  SIGN_IN_START: 'SIGN_IN_START',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAIL: 'SIGN_IN_FAIL',

  SIGN_OUT_START: 'SIGN_OUT_START',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
  SIGN_OUT_FAIL: 'SIGN_OUT_FAIL',

  ACCOUNT_DETAILS_START: 'ACCOUNT_DETAILS_START',
  ACCOUNT_DETAILS_SUCCESS: 'ACCOUNT_DETAILS_SUCCESS',
  ACCOUNT_DETAILS_FAIL: 'ACCOUNT_DETAILS_FAIL',
};

export const notificationActions = {
  NOTIFICATION_REMOVE: 'NOTIFICATION_REMOVE',
  NOTIFICATION_CREATE: 'NOTIFICATION_CREATE',
};